services:
  tor1:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor1
    restart: unless-stopped
    ports:
      - "9050:9050"
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    environment:
      - TOR_NICKNAME=relay1

  tor2:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor2
    restart: unless-stopped
    ports:
      - "9051:9050"
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    environment:
      - TOR_NICKNAME=relay2

  tor3:
    image: peterdavehello/tor-socks-proxy:latest
    container_name: tor3
    restart: unless-stopped
    ports:
      - "9052:9050"
    volumes:
      - ./torrc:/etc/tor/torrc:ro
    environment:
      - TOR_NICKNAME=relay3

  haproxy:
    image: haproxy:2.8
    container_name: tor-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "1080:1080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - tor1
      - tor2
      - tor3

  tor-rotator:
    image: alpine:latest
    container_name: tor-rotator
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./rotate.sh:/tmp/rotate.sh:ro
    command: sh -c "apk add --no-cache docker-cli && cp /tmp/rotate.sh /rotate.sh && chmod +x /rotate.sh && /rotate.sh"
    depends_on:
      - tor1
      - tor2
      - tor3
